[localhost]
localhost ansible_connection=local

[anginix_docker_ec2]
"IP_ADDRESS"ansible_user=ubuntu ansible_ssh_private_key_file=/home/unknown/Documents/tkxeldevops.pem

[jenkins_worker_node]
"IP_ADDRESS" ansible_user=ubuntu ansible_ssh_private_key_file=/home/unknown/Documents/tkxeldevops.pem