[localhost]
localhost ansible_connection=local

[anginix_docker_ec2]
[anginix_docker_ec2_url] ansible_user=ubuntu ansible_ssh_private_key_file= [ssh_key_path]

[jenkins_worker_node]
[jenkins_worker_node_url] ansible_user=ubuntu ansible_ssh_private_key_file= [ssh_key_path]
